# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Titulo', models.CharField(max_length=50)),
                ('Publicacion', models.TextField()),
                ('Slug', models.SlugField(editable=False)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
    ]
